[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
